'$schema' = 'https://starship.rs/config-schema.json'

format = '''
[󰇝](239) $directory( $git_branch$git_commit$git_status)( $git_state)( [󰇝](239) $nodejs)( [󰇝](239) $python)( [󰇝](239) $rust)
$character
'''

right_format = '[ $hostname $memory_usage ](fg:059 bg:233)'
command_timeout = 1000

[character]
error_symbol = '[󰄾](067)'
success_symbol = '[󰄾](067)'

[directory]
format = '[$path]($style)( [$read_only]($read_only_style))'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)( [$read_only]($read_only_style))'
before_repo_root_style = '059'
fish_style_pwd_dir_length = 1
read_only = ''
read_only_style = 'yellow'
repo_root_style = '033 underline'
style = '033'
truncate_to_repo = true
truncation_length = 0

[git_branch]
format = '[[ $branch](081)(:[$remote_branch](red))](059)'

[git_commit]
format = '[\[[$hash](yellow)(:[$tag](purple))\]](059)'
commit_hash_length = 8
only_detached = false
tag_disabled = false
tag_symbol = ''

[git_state]
format = '[$state( $progress_current/$progress_total)](bright-yellow underline)'

[git_status]
format = '([<$renamed$staged$index_deleted$modified$worktree_deleted$conflicted$untracked>](059))( $ahead_behind)( $stashed)'
ahead = '[󱦲](118)'
behind = '[󱦳](red)'
conflicted = '[$count](162)'
diverged = '[󰘖](red)'
index_deleted = '[$count](green strikethrough)'
modified = '[$count](208)'
renamed = '[$count](blue)'
staged = '[$count](green)'
stashed = '[ $count](yellow dimmed)'
untracked = '$count'
worktree_deleted = '[$count](208 strikethrough)'

[hostname]
format = ' $hostname'
ssh_only = false

[memory_usage]
format = ' $ram'
disabled = false
threshold = 0

[nodejs]
format = '[ $version](green)'
version_format = '$raw'

[python]
format = '[󰌠 $version](yellow)'
version_format = '$raw'

[rust]
format = '[󱘗 $version](red)'
version_format = '$raw'
